### ISSUE TITLE
Hero Video調整

### ISSUE THREAD

**Issue by renddiyeh** [indexhui/realengine-homepage#1]
用影片作為底圖OK，但目前字蓋掉太多影片
可以調整成第一句話大
第二句小(電腦版控制在兩行字以內
合作洽詢可以先拿掉
![image](https://user-images.githubusercontent.com/3462696/154198937-650453e1-e566-4474-87b2-d5a758bbba1b.png)

**Comment by indexhui** [comment]
![image](https://user-images.githubusercontent.com/19654281/155095123-c33f4c8c-722a-4b2e-bde6-b2c57afe8bc7.png)
