### ISSUE TITLE
一些順序及位置調整

### ISSUE THREAD

**Issue by renddiyeh** [indexhui/realengine-homepage#2]
在專業團隊之下，加入合作洽詢的按鈕
大，框線模式式

調換合作夥伴順序，移到精選專案後面

進行中專案，要加排只有1個專案的版型，不然到時會太孤單

精選專案，調整成一排4個，然後做成carousel
![image](https://user-images.githubusercontent.com/3462696/154199471-acd20644-41cf-4a73-8774-f1aa7ff1e49d.png)

**Comment by indexhui** [comment]
"在專業團隊之下，加入合作洽詢的按鈕
大，框線模式式"  想問明確位置

**Comment by renddiyeh** [comment]
這兒~
![image](https://user-images.githubusercontent.com/3462696/155166999-610361af-ab8a-4200-bd0d-64e41de0cb44.png)

**Comment by indexhui** [comment]
> 這兒~ ![image](https://user-images.githubusercontent.com/3462696/155166999-610361af-ab8a-4200-bd0d-64e41de0cb44.png)

了解 想說是文字下還是區塊下XD

**Comment by indexhui** [comment]
![React App](https://user-images.githubusercontent.com/19654281/157612682-c4894e76-89f0-4386-80c2-8a98efeb4675.png)
![React App](https://user-images.githubusercontent.com/19654281/157612686-2cfa4eb5-2939-4015-982d-87393ad0fa51.png)
![React App](https://user-images.githubusercontent.com/19654281/157612694-63e7eef1-1859-426b-87dd-27dc2916f084.png)
