### ISSUE TITLE
精選專案的排版

### ISSUE THREAD

**Issue by renddiyeh** [indexhui/realengine-homepage#3]
精選專案的排版，要做成高度一樣高，最後的字都置底
![image](https://user-images.githubusercontent.com/3462696/154200168-eac8bd9e-9a44-4c2a-a22a-12e107345c86.png)

**Comment by indexhui** [comment]
![image](https://user-images.githubusercontent.com/19654281/155096220-d93edde7-d5d3-4cc4-9b05-a60dcb8e7e75.png)
已修正
