### ISSUE TITLE
粉絲回饋的高度

### ISSUE THREAD

**Issue by renddiyeh** [indexhui/realengine-homepage#4]
![image](https://user-images.githubusercontent.com/3462696/154201724-0a1cadd6-56c4-41b3-a51c-78328a5448ae.png)
希望可以等高

**Comment by indexhui** [comment]
@renddiyeh 
我需要你的建議
![image](https://user-images.githubusercontent.com/19654281/155100860-5a9ef798-c28d-435a-8de8-85be07667025.png)
目前解決但是用寫死
這個是被slick產生的div 包起來 ，不知道怎麼寫讓他們自動等高

**Comment by renddiyeh** [comment]
話說，我發現另一個問題
boxshadow是不是被slick的邊界裁掉了

**Comment by indexhui** [comment]
哦喔 但那個 feature 這邊就有了
 https://indexhui.github.io/realengine-homepage/  
我把它復刻了
